name: publish

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/publish.yaml'
      - 'tsconfig.json'
      - 'tsconfig.test.json'
      - 'jest.config.js'

permissions: write-all

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v6

      - name: ⚡ Setup pnpm
        uses: pnpm/action-setup@v5

      - name: ❇️ Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: jod/iron
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml

      - name: ⬇️ Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: 🛠️ Build
        run: pnpm bundler:build

      - name: 🧑‍🔬 Execute Tests
        run: npm bundler:test

      - name: 📊 Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './apps/electron-app-bundler/ctrf/*.json'
        if: always()

  release:
    name: 🚀 Publish
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 🚀 Release in repository
        uses: justincy/github-action-npm-release@2.0.2
        id: release

      - name: ❇️ Setup Node
        if: steps.release.outputs.released == 'true'
        uses: actions/setup-node@v6
        with:
          node-version: jod/iron
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml

      - name: 📥 Install Dependencies
        if: steps.release.outputs.released == 'true'
        run: pnpm install --frozen-lockfile

      - name: 🛠️ Build
        if: steps.release.outputs.released == 'true'
        run: pnpm bundler:build

      - name: 🚀 Publish to npm
        uses: JS-DevTools/npm-publish@v3
        if: steps.release.outputs.released == 'true'
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          access: public
          provenance: true
